<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR9HT99q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR9HT99q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR9HT99q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR9HT99q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR9HT99q\App_KernelDevDebugContainer([
    'container.build_hash' => 'R9HT99q',
    'container.build_id' => 'ef3eccc7',
    'container.build_time' => 1606746413,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR9HT99q');
